"import re"  
""  
"FILE_PATH = 'agent_orchestrator.py'"  
""  
"with open(FILE_PATH, 'r', encoding='utf-8') as f:"  
"    lines = f.readlines()"  
""  
"fixed_count = 0"  
""  
"for i in range(len(lines)):"  
"    if 'reasoning = f' in lines[i] and 'm.get' in lines[i-1]:"  
"        indent = len(lines[i]) - len(lines[i].lstrip())"  
"        pre_strip = ' ' * indent + '# Strip any nested think tags from reasoning_content to prevent conflicting blocks\n'"  
