"""
API Router — Multi-endpoint API selection with priority-based fallback.

Manages a pool of named LLM API endpoints. Each agent *type* (orchestrator,
coder, researcher…) can have its own priority-ordered list of endpoints.
The General Settings API (default_llm_cfg) is always the last-resort fallback.

Persistence: workspace/config/api_endpoints.json
"""

import collections
import copy
import json
import logging
import os
import random
import threading
import time
import traceback
import uuid
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Callable, Deque, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

from agent_cascade.settings import (
    ENDPOINT_SLOT_ACQUIRE_TIMEOUT,
    ENDPOINT_COOLDOWN_SECONDS,
    ENDPOINT_FAILURE_CLEANUP_HOURS,
)
from agent_cascade.exceptions import ContextWindowExceeded, AgentTerminatedError
from agent_cascade.retry_policy import calculate_backoff, RetryPolicy, POLICY_DEFAULT
from agent_cascade.slot_queue import SlotPool, QUEUE_WAIT_TIMEOUT


# ── Termination check helpers (used by interruptible sleep patterns) ─────────

def _check_termination(pool, instance_name: str) -> bool:
    """Check if an instance has been terminated/dismissed.
    
    Returns True if the instance should abort its current operation.
    Safe to call with None pool or empty instance_name — returns False.
    """
    if not pool or not instance_name:
        return False
    return pool.is_instance_terminated(instance_name)


def _interruptible_sleep(duration: float, pool, instance_name: str, interval: float = 0.5) -> None:
    """Sleep for duration seconds, checking termination every interval seconds.
    
    Raises AgentTerminatedError if the instance is terminated during the wait.
    """
    start = time.monotonic()
    while time.monotonic() - start < duration:
        if _check_termination(pool, instance_name):
            raise AgentTerminatedError(instance_name)
        remaining = duration - (time.monotonic() - start)
        time.sleep(min(interval, remaining))


# ── Lightweight config initializer (used by shared_init before APIRouter loads) ─────────

def ensure_api_endpoints_config(config_dir: Optional[str] = None) -> bool:
    """
    Ensure api_endpoints.json exists at startup without instantiating APIRouter.

    Returns True if the file already existed or was created successfully, False on failure.
    """
    try:
        if config_dir is not None:
            config_path = Path(config_dir) / 'api_endpoints.json'
        else:
            # Project-root config dir (same logic as APIRouter.__init__)
            project_root = Path(__file__).resolve().parent.parent
            config_path = project_root / 'config' / 'api_endpoints.json'

        if config_path.exists():
            return True

        config_path.parent.mkdir(parents=True, exist_ok=True)
        default_config = {
            "endpoints": [],
            "agent_priorities": {},
            "agent_types_with_priorities": [],
        }
        with open(config_path, 'w', encoding='utf-8') as f:
            json.dump(default_config, f, indent=2)

        logger.warning(
            "config/api_endpoints.json not found; created with empty default configuration. "
            "Please configure at least one LLM endpoint."
        )
        return True
    except OSError as e:
        logger.error("[INIT] Failed to create config/api_endpoints.json: %s", e)
        return False

MAX_CAPTION_LENGTH = 300              # Maximum length for image captions generated by vision model
RATE_LIMIT_WINDOW_SECONDS = 60        # Sliding window (seconds) for per-endpoint rate-limit tracking

# Canonical agent type mapping for case-insensitive normalization and idempotency
# Maps lowercase agent types to their canonical PascalCase form
CANONICAL_AGENT_TYPES: Dict[str, str] = {
    "coder": "Coder",
    "researcher": "Researcher",
    "orchestrator": "Orchestrator",
    "security": "Security",
    "writer": "Writer",
    "reviewer": "Reviewer",
    "compressor": "Compressor",
    "generalist": "Generalist",
}


# ── Data Models ──────────────────────────────────────────────────────────────

@dataclass
class APIEndpoint:
    """A single LLM API endpoint configuration."""
    id: str = ""                       # UUID, auto-generated if empty
    name: str = "Unnamed Endpoint"     # Human-friendly label
    api_base: str = ""                 # e.g. "http://localhost:1234/v1"
    api_key: str = "EMPTY"             # API key (may be "EMPTY" for local)
    model: str = ""                    # Model name/ID
    model_type: str = "qwenvl_oai"     # "qwenvl_oai", "openai", etc.
    enabled: bool = True               # Toggle on/off without deleting
    max_retries: int = 1               # Per-endpoint retry count before moving to next
    concurrency_limit: int = -1        # -1 = unlimited, 0 = sequential delegation, 1+ = max parallel requests
    max_input_tokens: int = 0          # 0 = unlimited/auto, 1+ = specific limit for this model
    rate_limit_rpm: int = 0            # Rate limit in requests per minute (0 = unlimited)

    # ── Sampler parameters (per-endpoint overrides) ──────────────────────
    temperature: float = 0.0           # 0.0 = use global/default
    top_p: float = 0.0                 # 0.0 = use global/default
    top_k: int = 0                     # 0 = use global/default
    min_p: float = 0.0                 # 0.0 = use global/default
    repeat_penalty: float = 0.0        # 0.0 = use global/default
    presence_penalty: float = 0.0      # 0.0 = use global/default
    frequency_penalty: float = 0.0     # 0.0 = use global/default
    max_tokens: int = 0                # 0 = use global/default

    vision_enabled: bool = True        # Whether this endpoint supports vision
    use_custom_sampling: bool = False  # Master toggle — if False, all sampler params above are ignored
    state_save_enabled: bool = False   # Enable KV cache state save/restore (autoloader only)

    def __post_init__(self):
        if not self.id:
            self.id = str(uuid.uuid4())

    def to_llm_cfg(self) -> dict:
        """Convert to the llm_cfg dict format used by agent_cascade.

        When use_custom_sampling is True, per-endpoint sampler parameters are included.
        Only non-zero values override — zero/empty sentinel values mean "use global/default".
        """
        cfg = {
            'model': self.model,
            'model_server': self.api_base,
            'api_base': self.api_base,
            'api_key': self.api_key,
            'model_type': self.model_type,
            'max_input_tokens': self.max_input_tokens,
            # NOTE: max_retries intentionally excluded — endpoint retry config controls L2 (API router) only.
            # L1 retries are disabled (see llm/base.py). Including this here was the source of coupling.
            'vision_enabled': self.vision_enabled,  # Vision capability flag for routing decisions
            'state_save_enabled': self.state_save_enabled,  # KV cache state save/restore toggle (autoloader only)
        }

        # Signal to _build_merged_cfg whether custom sampling is enabled for this endpoint.
        # When disabled, the merge should strip stale sampling params from lower layers
        # (template defaults / UI overrides) so they don't leak into the LLM call.
        cfg['_use_custom_sampling'] = self.use_custom_sampling

        if self.use_custom_sampling:
            # Only include non-zero sampler params (zero = "use default")
            # Using != 0 consistently so negative values are also captured where valid
            if self.temperature != 0:
                cfg['temperature'] = self.temperature
            if self.top_p != 0:
                cfg['top_p'] = self.top_p
            if self.top_k != 0:
                cfg['top_k'] = self.top_k
            if self.min_p != 0:
                cfg['min_p'] = self.min_p
            rp = self.repeat_penalty
            if rp != 0:
                _normalize_repeat_penalty(cfg, 'repeat_penalty', rp)
            if self.presence_penalty != 0:
                cfg['presence_penalty'] = self.presence_penalty
            if self.frequency_penalty != 0:
                cfg['frequency_penalty'] = self.frequency_penalty
            if self.max_tokens != 0:
                cfg['max_tokens'] = self.max_tokens

        return cfg

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> 'APIEndpoint':
        if not isinstance(data, dict):
            return cls()
        # Filter to only known fields to prevent TypeError on unexpected keys
        known = {f.name for f in cls.__dataclass_fields__.values()}
        filtered = {k: v for k, v in data.items() if k in known}
        return cls(**filtered)

def _normalize_repeat_penalty(cfg: dict, key: str = 'repeat_penalty', val=None) -> None:
    """Add repeat_penalty key variants for backend compatibility.

    If *val* is provided it is used directly; otherwise the value is read from cfg[key].
    All three common naming conventions are written via setdefault so existing entries
    (e.g. already loaded from a config file) take precedence.
    """
    if val is None:
        val = cfg.get(key)
    if val is not None:
        cfg.setdefault('repeat_penalty', val)
        cfg.setdefault('repetition_penalty', val)
        cfg.setdefault('repeatPenalty', val)


# ── Endpoint Scheduler (Lifecycle-aware serialization) ───────────────────────

class EndpointScheduler:
    """
    Manages per-API-base scheduling with lifecycle-aware serialization.
    
    Phase 2: Uses SlotPool per endpoint for FIFO queueing + strict capacity control.
    For concurrency=0 endpoints: agents are strictly serialized — one at a time,
    from task submission to full completion (including all LLM calls and tool waits).
    All concurrency=0 endpoints share the SAME slot to avoid cache trashing from
    interleaving across different API addresses.
    For concurrency=N endpoints: at most N agents can run simultaneously.
    For concurrency=-1 endpoints: no scheduling needed (unlimited).
    
    This operates at the AGENT TASK level (entire agent lifecycle), NOT the
    individual API call level. This prevents interleaving of LLM calls between
    different agents on the same endpoint.

    Uses SlotPool per endpoint for FIFO queueing + strict capacity control.
    """
    
    def __init__(self):
        self._lock = threading.RLock()
        # Per-endpoint SlotPool for FIFO queueing + capacity control.
        # api_base -> SlotPool(key=api_base, capacity=N)
        self._pools: Dict[str, SlotPool] = {}
        # Lazy counter for acquisition IDs (for backward compat with diagnostics).
        self._next_acquisition_id = 0

    def _get_or_create_pool(self, api_base: str, concurrency_limit: int) -> Optional[SlotPool]:
        """Get or lazily create a SlotPool for the given endpoint.
        
        Args:
            api_base: The API base URL of the endpoint
            concurrency_limit: -1=unlimited, 0=sequential, N>0=max parallel
            
        Returns:
            SlotPool instance, or None if unlimited (-1).
        """
        if concurrency_limit == -1:
            return None
        
        # BUG FIX: All concurrency=0 endpoints share the same slot to avoid cache trashing.
        is_sequential = (concurrency_limit == 0)
        slot_key = '_shared_sequential_slot_' if is_sequential else api_base
        
        capacity = concurrency_limit if concurrency_limit > 0 else 1  # 0→1 (sequential)
        
        with self._lock:
            if slot_key not in self._pools:
                pool = SlotPool(key=slot_key, capacity=capacity)
                self._pools[slot_key] = pool
                logger.info(f"[EndpointScheduler] Created pool '{slot_key}' with capacity={capacity}")
            return self._pools[slot_key]
    
    def acquire(
        self,
        api_base: str,
        concurrency_limit: int,
        instance_name: str = "unknown",
        agent_class: str = "unknown",
        pool=None,
        timeout: Optional[float] = None,
        **kwargs,
    ) -> Optional[Callable[[], None]]:
        """
        Acquire a slot on the endpoint. Blocks if at capacity.
        Returns a cleanup callback to release the slot, or None if unlimited.
        
        Uses SlotPool.acquire() for FIFO queueing + strict capacity control.
        
        Args:
            api_base: The API base URL of the endpoint
            concurrency_limit: -1=unlimited, 0=sequential, N>0=max parallel
            instance_name: Name of the agent instance acquiring the slot (for tracking)
            agent_class: Class of the agent instance (for tracking)
            pool: Optional AgentPool reference for termination checks during blocking acquire
            timeout: Optional override for wait timeout in seconds
            
        Returns:
            A callable that releases the slot when called, or None if no scheduling needed.
            
        Raises:
            TimeoutError: If slot cannot be acquired within ENDPOINT_SLOT_ACQUIRE_TIMEOUT.
            AgentTerminatedError: If instance is terminated while waiting.
        """
        if concurrency_limit == -1:  # unlimited — no scheduling needed
            logger.debug(f"[CALL_AGENT_DEBUG] EndpointScheduler.acquire — api_base={api_base}, concurrency=-1 (unlimited), returning None")
            return None
        
        # BUG FIX: All concurrency=0 endpoints share the same slot to avoid cache trashing.
        is_sequential = (concurrency_limit == 0)
        slot_key = '_shared_sequential_slot_' if is_sequential else api_base
        
        logger.debug(
            f"[CALL_AGENT_DEBUG] EndpointScheduler.acquire — api_base={api_base}, "
            f"concurrency_limit={concurrency_limit}, slot_key={slot_key}, "
            f"instance_name={instance_name}, agent_class={agent_class}"
        )
        
        # Get or create the pool (handles lazy initialization + capacity mapping).
        sched_pool = self._get_or_create_pool(api_base, concurrency_limit)
        if sched_pool is None:
            return None
        
        # Use QUEUE_WAIT_TIMEOUT (300s) as primary; ENDPOINT_SLOT_ACQUIRE_TIMEOUT as fallback for backward compat.
        effective_timeout = timeout if timeout is not None else (QUEUE_WAIT_TIMEOUT or ENDPOINT_SLOT_ACQUIRE_TIMEOUT)
        
        try:
            # Phase 2: Call SlotPool.acquire() — FIFO queueing, strict capacity, interruptible ticks.
            release_from_pool = sched_pool.acquire(
                instance_name=instance_name,
                agent_class=agent_class,
                timeout=effective_timeout,
            )
            
            logger.info(f"[EndpointScheduler] Agent '{instance_name}' ({agent_class}) acquired slot on '{api_base}' "
                       f"(pool={slot_key}, active={len(sched_pool._running)}, capacity={sched_pool.capacity})")
            
            # Wrap the pool's release callback to preserve existing logging behavior.
            def release():
                try:
                    release_from_pool()
                except Exception as e:
                    log_target = api_base if not is_sequential else f"{api_base} (shared sequential)"
                    logger.error(f"[SLOT_RELEASE_ERROR] Failed to release slot for {log_target}: {e}", exc_info=True)
                    return
                
                # Log release with current pool stats.
                log_target = api_base if not is_sequential else f"{api_base} (shared sequential)"
                logger.info(f"[EndpointScheduler] Agent '{instance_name}' ({agent_class}) released slot on '{log_target}' "
                           f"(pool={slot_key}, active={len(sched_pool._running)}, capacity={sched_pool.capacity})")
            
            return release
            
        except TimeoutError as e:
            # Wrap with holder info for diagnostics.
            holder_info = ""
            holders = list(sched_pool._running.values())
            if holders:
                holder_names = [f"{h.instance_name} ({h.agent_name})" for h in holders]
                holder_info = f". Currently held by: {', '.join(holder_names)}"
            
            raise TimeoutError(
                f"Timed out after {timeout}s waiting for endpoint slot on {api_base}. "
                f"Current active count: {len(sched_pool._running)}, max allowed: {sched_pool.capacity}{holder_info}"
            ) from e
        
        except Exception as e:
            # Catch-all for unexpected errors during acquire.
            logger.error(f"[EndpointScheduler] Acquire failed for '{instance_name}' on '{api_base}': {e}", exc_info=True)
            raise
    
    def count_active(self, api_base: str, concurrency_limit: int) -> int:
        """Count active tasks on an endpoint.
        
        Args:
            api_base: The API base URL of the endpoint
            concurrency_limit: -1=unlimited, 0=sequential, N>0=max parallel
            
        Returns:
            Number of currently active agents on this endpoint
        """
        if concurrency_limit == -1:
            return 0
        
        slot_key = '_shared_sequential_slot_' if concurrency_limit == 0 else api_base
        pool = self._pools.get(slot_key)
        return len(pool._running) if pool else 0
    
    def get_status(self) -> Dict[str, Dict]:
        """Get status of all scheduled endpoints (for diagnostics).
        
        Returns:
            Dictionary mapping endpoint identifiers to their current status.
            Shared sequential slots are labeled as '[SHARED] _shared_sequential_slot_'
            to distinguish them from per-endpoint schedules.
        """
        result = {}
        for key, pool in self._pools.items():
            display_key = f"[SHARED] {key}" if 'shared' in key.lower() else key
            
            # Build slot holders info from pool._running (SlotHolder has instance_name, agent_name).
            holders_info = []
            for holder in pool._running.values():
                held_duration = time.monotonic() - holder.granted_at
                holders_info.append({
                    'instance_name': holder.instance_name,
                    'agent_class': holder.agent_name,  # agent_name used as display name
                    'held_duration_seconds': held_duration,
                })
            
            result[display_key] = {
                'active_count': len(pool._running),
                'max_active': pool.capacity,
                'available_slots': pool.capacity - len(pool._running),
                'waiters_count': len(pool._waiters),
                'slot_holders': holders_info,
            }
        return result
    
    def cleanup_stale(self):
        """Remove schedule entries for endpoints with no activity.
        
        A pool is stale when _running is empty AND _waiters is empty (no active or waiting agents).
        This prevents memory leaks from endpoints that were used temporarily and have since gone idle.
        
        Note: The shared sequential slot (_shared_sequential_slot_) is NOT cleaned up
        to avoid unnecessary recreation of the shared pool across different
        concurrency=0 endpoints.
        """
        with self._lock:
            stale = [key for key, pool in self._pools.items()
                     if key != '_shared_sequential_slot_'  # Protect shared slot from cleanup
                     and len(pool._running) == 0 and len(pool._waiters) == 0]
            for key in stale:
                del self._pools[key]
            if stale:
                logger.info(f"[EndpointScheduler] Cleaned up {len(stale)} stale schedule(s)")

    def get_slot_holders(self, slot_key: str = None) -> Dict[str, List[tuple]]:
        """Get information about which instances are holding slots.
        
        Phase 2: Returns data from SlotPool._running as tuples for backward compat.
        
        Args:
            slot_key: Optional specific slot key to query. If None, returns all.
            
        Returns:
            Dictionary mapping slot keys to lists of
            (instance_name, agent_name, granted_at, acquisition_id) tuples.
            NOTE: SlotHolder.agent_name is populated with the instance name by
            _grant() in slot_queue.py (the agent_class is not stored on the holder),
            so tuple[1] is the instance/agent name, not a class string.
        """
        import copy
        result = {}
        
        if slot_key:
            pool = self._pools.get(slot_key)
            if pool:
                holders = [(h.instance_name, h.agent_name, h.granted_at, h.acquisition_id) 
                           for h in pool._running.values()]
                result[slot_key] = copy.deepcopy(holders)
        else:
            for key, pool in self._pools.items():
                holders = [(h.instance_name, h.agent_name, h.granted_at, h.acquisition_id) 
                           for h in pool._running.values()]
                if holders:
                    result[key] = copy.deepcopy(holders)
        
        return result

    def detect_stuck_slots(self, threshold_seconds: float = 60.0) -> List[dict]:
        """Detect slots that have been held for longer than the threshold.
        
        Phase 2: Uses SlotPool._running to check hold durations.
        
        Args:
            threshold_seconds: Time in seconds after which a slot is considered "stuck"
            
        Returns:
            List of dictionaries with information about stuck slots, including:
            - slot_key: The slot identifier
            - instance_name: Name of the holding instance
            - agent_class: Class of the holding instance  
            - held_duration: How long the slot has been held (seconds)
            - acquired_at: Timestamp when slot was acquired
        """
        stuck_slots = []
        current_time = time.monotonic()
        
        # Check held slots — _running access is safe without lock for diagnostics.
        for key, pool in self._pools.items():
            with pool._cond:
                holders_snapshot = list(pool._running.values())
            for holder in holders_snapshot:
                held_duration = current_time - holder.granted_at
                if held_duration > threshold_seconds:
                    stuck_slots.append({
                        'slot_key': key,
                        'instance_name': holder.instance_name,
                        'agent_class': holder.agent_name,
                        'held_duration': held_duration,
                        'acquired_at': holder.granted_at,
                    })
                    logger.warning(
                        f"[SLOT_STUCK_DETECTION] Slot on '{key}' held by '{holder.instance_name}' "
                        f"({holder.agent_name}) for {held_duration:.1f}s (threshold: {threshold_seconds}s)"
                    )
        
        # Flag waiters older than QUEUE_WAIT_TIMEOUT.
        # Copy data under lock with short critical section, then iterate outside.
        for key, pool in self._pools.items():
            with pool._cond:
                waiters_snapshot = list(pool._waiters.values())
            
            # Flag aged waiters (outside lock)
            for ticket in waiters_snapshot:
                age = current_time - ticket.created_at
                if age > QUEUE_WAIT_TIMEOUT:
                    stuck_slots.append({
                        'slot_key': key,
                        'instance_name': ticket.instance_name,
                        'agent_class': ticket.agent_class,
                        'held_duration': age,
                        'acquired_at': ticket.created_at,
                        'issue': 'waiter_expired',
                    })
                    logger.warning(
                        f"[SLOT_STUCK_DETECTION] Waiter '{ticket.instance_name}' on '{key}' "
                        f"has waited {age:.1f}s > QUEUE_WAIT_TIMEOUT={QUEUE_WAIT_TIMEOUT}s"
                    )
        
        return stuck_slots
    
    def get_slot_info(self, api_base: str, concurrency_limit: int) -> dict:
        """Get slot information for an endpoint without acquiring.
        
        Returns dict with:
          - slot_key: The internal key used ('_shared_sequential_slot_' or api_base)
          - is_sequential: True if conc=0 (shared sequential pool)
          - concurrency_limit: The effective limit (-1, 0, or N>0)
        """
        is_sequential = (concurrency_limit == 0)
        slot_key = '_shared_sequential_slot_' if is_sequential else api_base
        
        return {
            'slot_key': slot_key,
            'is_sequential': is_sequential,
            'concurrency_limit': concurrency_limit,
        }
    



    def cancel(self, instance_name: str = None, ticket_id: str = None) -> bool:
        """Cancel a waiting ticket in the queue.
        
        Called during termination to remove pending waiters from the queue.
        
        Args:
            instance_name: Cancel all tickets for this agent.
            ticket_id: Cancel a specific ticket by ID.
            
        Returns:
            True if any ticket was cancelled, False otherwise.
        """
        for pool in self._pools.values():
            if ticket_id:
                if pool.cancel(ticket_id=ticket_id):
                    logger.debug(f"[CANCELLATION] Cancelled ticket {ticket_id}")
                    return True
            elif instance_name:
                count = pool.cancel(agent_name=instance_name)
                if count > 0:
                    logger.info(f"[CANCELLATION] Cancelled {count} ticket(s) for {instance_name}")
                    return True
        
        return False

    def cancel_all(self) -> int:
        """Cancel ALL waiting tickets across all pools.
        
        Called during stop_session() to clean up all pending waiters.
        
        Returns:
            Total number of tickets cancelled.
        """
        total = 0
        for pool in self._pools.values():
            count = len(pool._waiters)
            if count > 0:
                with pool._cond:
                    for ticket in pool._waiters.values():
                        ticket.cancelled.set()
                    pool._waiters.clear()
                    pool._cond.notify_all()
                total += count
        
        if total > 0:
            logger.info(f"[CANCELLATION] Cancelled {total} total tickets across all pools")
        
        return total
    
    def terminate_for_agent(self, agent_name: str) -> tuple:
        """Cancel all tickets for an agent.
        
        Called during AgentInstance.terminate() to fully clean up that agent's
        presence in all scheduling queues.
        
        Args:
            agent_name: Name of the agent to terminate from queues.
            
        Returns:
            Tuple of (tickets_cancelled, 0) for backward-compat with callers.
        """
        tickets = 0
        
        for pool in self._pools.values():
            # Cancel all waiting tickets for this agent.
            with pool._cond:
                to_remove = [tid for tid, t in pool._waiters.items() if t.instance_name == agent_name]
                for tid in to_remove:
                    pool._waiters[tid].cancelled.set()
                    pool._waiters.pop(tid)
                    tickets += 1
                pool._cond.notify_all()
        
        if tickets > 0:
            logger.info(f"[TERMINATION] Cleaned up {agent_name}: {tickets} ticket(s)")
        
        return (tickets, 0)


# ── API Router ───────────────────────────────────────────────────────────────

class APIRouter:
    """
    Manages multi-endpoint API selection with priority-based fallback.

    The General Settings API (``default_llm_cfg``) is always available as the
    last-resort endpoint for every agent type.
    """

    def __init__(
        self,
        default_llm_cfg: dict,
        config_dir: Optional[str] = None,
        policy: Optional[RetryPolicy] = None,
    ):
        """
        Args:
            default_llm_cfg: The main LLM config from General Settings. This
                            is always the last-resort fallback and is never deleted.
            config_dir:     Directory to persist api_endpoints.json.
                            Defaults to workspace/config.
            policy:         RetryPolicy governing retry behavior. Controls both
                            per-endpoint max retries (endpoint_max_retries) and
                            backoff parameters (base_delay, max_delay, jitter_factor).
                            Falls back to POLICY_DEFAULT if not provided.
        """
        self.default_llm_cfg = default_llm_cfg
        self.policy = policy or POLICY_DEFAULT
        self.endpoints: Dict[str, APIEndpoint] = {}           # id → endpoint
        self.agent_priorities: Dict[str, List[str]] = {}      # agent_type → [endpoint_ids]
        self._agent_types_with_priorities: set = set()        # Agent types with active endpoint priorities (gates Tier 3 last-successful fallback)
        self._lock = threading.Lock()
        self._pool = None  # Set externally by AgentPool when router is attached

        # Lifecycle-aware endpoint scheduler for parallel agent management.
        # Acquires a slot at task submission time and holds it for the entire
        # agent lifecycle — prevents interleaving of LLM calls between agents.
        self.scheduler = EndpointScheduler()
        # Phase 3: Give scheduler a reference back to this router for endpoint resolution.
        self.scheduler._router_ref = self

        # Track the last successfully used endpoint config for automatic recovery.
        # When an agent's configured endpoints become unavailable, this provides
        # a validated fallback that previously succeeded (Tier 2 in fallback chain).
        self._last_successful_endpoint_cfg: Optional[Dict[str, Any]] = None

        # Rate limiting: track call timestamps per endpoint for rate limit enforcement.
        # api_base -> deque of timestamps (seconds since epoch) for efficient sliding window.
        self._endpoint_call_history: Dict[str, Deque[float]] = {}

        # Cooldown tracking: api_base -> last failure timestamp (epoch seconds).
        # Failed endpoints are skipped during cooldown to prevent hammering dead servers.
        self._endpoint_failure_times: Dict[str, float] = {}

        # Per-instance endpoint cursor for "kick to next endpoint" behavior (thread-safe via self._lock).
        self._instance_endpoint_position: Dict[str, int] = {}

        # Persistence path — env var takes precedence for test isolation
        if os.environ.get("AGENT_CASCADE_TEST_CONFIG_DIR"):
            self._config_dir = Path(os.environ["AGENT_CASCADE_TEST_CONFIG_DIR"])
        elif config_dir:
            self._config_dir = Path(config_dir)
        else:
            # API config lives in the project root config/ dir, not workspace
            project_root = Path(__file__).resolve().parent.parent
            self._config_dir = project_root / 'config'
        self._config_path = self._config_dir / 'api_endpoints.json'

        # Load persisted config if available
        self._load()

    # ── Endpoint CRUD ────────────────────────────────────────────────────

    def add_endpoint(self, endpoint: APIEndpoint) -> str:
        """Add or update an endpoint. Returns the endpoint ID."""
        with self._lock:
            if not endpoint.id:
                endpoint.id = str(uuid.uuid4())
            self.endpoints[endpoint.id] = endpoint
            self._save()
            return endpoint.id

    def remove_endpoint(self, endpoint_id: str) -> bool:
        """Remove an endpoint by ID. Returns True if removed."""
        with self._lock:
            if endpoint_id not in self.endpoints:
                return False
            # Get the api_base before deleting to clean up related state
            endpoint_api_base = self.endpoints[endpoint_id].api_base
            del self.endpoints[endpoint_id]
            
            # Clean up rate limit history for this endpoint's api_base
            if endpoint_api_base in self._endpoint_call_history:
                del self._endpoint_call_history[endpoint_api_base]
            
            # Also clean up any agent_priorities referencing this endpoint
            for agent_type in list(self.agent_priorities.keys()):
                self.agent_priorities[agent_type] = [
                    eid for eid in self.agent_priorities[agent_type]
                    if eid != endpoint_id
                ]
                # Remove empty lists and clean up tracking set
                if not self.agent_priorities[agent_type]:
                    del self.agent_priorities[agent_type]
                    self._agent_types_with_priorities.discard(agent_type)
            self._save()
            return True

    def update_endpoint(self, endpoint_id: str, updates: dict) -> bool:
        """Partially update an existing endpoint. Returns True if found."""
        with self._lock:
            ep = self.endpoints.get(endpoint_id)
            if not ep:
                return False
            for k, v in updates.items():
                if hasattr(ep, k) and k != 'id':
                    setattr(ep, k, v)
            self._save()
            return True

    def get_endpoint(self, endpoint_id: str) -> Optional[APIEndpoint]:
        """Get a single endpoint by ID."""
        return self.endpoints.get(endpoint_id)

    def list_endpoints(self) -> List[APIEndpoint]:
        """Return all endpoints in insertion order."""
        with self._lock:
            return list(self.endpoints.values())

    # ── Agent Priority Management ────────────────────────────────────────

    def set_agent_priorities(self, agent_type: str, endpoint_ids: List[str]):
        """
        Set the priority-ordered endpoint list for an agent type.
        
        Performs case-insensitive key normalization to prevent duplicate keys
        when frontend (PascalCase) and backend (lowercase) both update priorities.
        """
        with self._lock:
            # Normalize to canonical case (existing key or input as-is)
            canonical = self._normalize_agent_type(agent_type)
            
            # If normalized key differs from input and input exists, remove it to prevent duplicates
            if canonical != agent_type and agent_type in self.agent_priorities:
                del self.agent_priorities[agent_type]
                self._agent_types_with_priorities.discard(agent_type)
            
            # Validate that all IDs exist
            valid_ids = [eid for eid in endpoint_ids if eid in self.endpoints]
            filtered_count = len(endpoint_ids) - len(valid_ids)
            
            if valid_ids:
                self.agent_priorities[canonical] = valid_ids
                self._agent_types_with_priorities.add(canonical)  # Track that this agent type was configured
                logger.info(f"[APIRouter.set_agent_priorities] {canonical} → {valid_ids} "
                           f"({'filtered ' + str(filtered_count) + ' invalid IDs, ' if filtered_count else ''}"
                           f"canonical key: {canonical})")
            elif canonical in self.agent_priorities:
                del self.agent_priorities[canonical]
                self._agent_types_with_priorities.discard(canonical)
                logger.info(f"[APIRouter.set_agent_priorities] Removed priorities for {canonical} "
                           f"(all {len(endpoint_ids)} IDs were invalid)")
            else:
                logger.debug(f"[APIRouter.set_agent_priorities] No action for {agent_type} "
                            f"(no valid IDs, no existing priorities)")
            self._save()

    def get_agent_priorities(self, agent_type: str) -> List[str]:
        """Get the endpoint ID list for a specific agent type."""
        with self._lock:
            normalized = self._normalize_agent_type(agent_type)
            return list(self.agent_priorities.get(normalized, []))

    def _resolve_own_endpoints(
        self,
        agent_type: str,
    ) -> Tuple[List[Tuple[str, 'EndpointConfig']], bool]:
        """
        Resolve the agent's OWN enabled endpoints (Tier 1).

        Returns:
            (list of (endpoint_id, endpoint_obj) tuples, had_own_endpoints flag)
            The list contains only enabled endpoints from the agent's own priority
            config. Empty if the agent has none configured/enabled.
            had_own_endpoints indicates if agent_type had its own enabled endpoints.

        NOTE: Tier-2 caller inheritance was removed — every agent meters against its
        own resolved endpoint pool (single FIFO slot system). Agents without their own
        endpoints fall through to Tier 3 (last-successful) / Tier 4 (global default) in
        get_endpoint_chain, exactly like any other unconfigured agent.
        """
        # Normalize agent_type for case-insensitive lookup (Fix Finding 1)
        normalized_agent_type = self._normalize_agent_type(agent_type)

        # Agent-specific priorities — check for enabled endpoints
        result = []
        has_enabled_endpoints = False
        for eid in self.agent_priorities.get(normalized_agent_type, []):
            ep = self.endpoints.get(eid)
            if ep and ep.enabled:
                has_enabled_endpoints = True
                result.append((eid, ep))

        return result, has_enabled_endpoints

    def get_effective_concurrency(self, agent_type: str) -> int:
        """
        Returns the concurrency limit of the actual endpoint that will be used
        for the given agent type. Falls back to default config if no endpoints match.

        Returns -1 only if truly unlimited (no endpoint config found at all).
        Returns 0 as a conservative default when the default config specifies an
        api_base but no matching endpoint exists in self.endpoints — this prevents
        unexpected parallel launches on unknown endpoints.
        
        Args:
            agent_type: The agent type to resolve concurrency for
        """
        defaults = self.default_llm_cfg or {}
        with self._lock:
            own_endpoints, _had_own = self._resolve_own_endpoints(agent_type)

            if own_endpoints:
                eid, ep = own_endpoints[0]
                logger.debug(
                    f"[ENDPOINT_CONCURRENCY] get_effective_concurrency — "
                    f"agent_type={agent_type}, endpoint_id={eid}, "
                    f"concurrency_limit={ep.concurrency_limit}"
                )
                return ep.concurrency_limit

            # Tier 3+: Fall back to default endpoint by api_base
            default_base = defaults.get('api_base') or defaults.get('model_server', '')
            for ep in self.endpoints.values():
                if ep.api_base == default_base:
                    return ep.concurrency_limit
        # Default config exists with an api_base but no matching endpoint found.
        # Return 0 (sequential) as a conservative safety measure rather than -1,
        # because the user has configured an endpoint — we just can't find it.
        if defaults.get('api_base') or defaults.get('model_server'):
            return 0
        # Truly no config at all — unlimited
        return -1
    
    def get_agent_slot_info(self, agent_class: str) -> dict:
        """Get the slot type that an agent_class would use.

        Args:
            agent_class: The class name of the agent

        Returns:
            Dict with keys: slot_key, is_sequential, concurrency_limit, api_base, needs_slot.
            When concurrency_limit is -1 (unlimited), slot_key and api_base will be None.
        """
        concurrency = self.get_effective_concurrency(agent_class)
        if concurrency == -1:
            return {
                'slot_key': None,
                'is_sequential': False,
                'concurrency_limit': -1,
                'api_base': None,
                'needs_slot': False,
            }

        llm_cfg = self.get_llm_config(agent_class)
        api_base = llm_cfg.get('api_base') or llm_cfg.get('model_server', 'unknown')

        slot_info = self.scheduler.get_slot_info(api_base, concurrency)
        slot_info['api_base'] = api_base
        slot_info['needs_slot'] = True

        return slot_info

    # ── LLM Config Resolution ────────────────────────────────────────────

    def get_llm_config(self, agent_type: str) -> dict:
        """
        Returns the highest-priority *enabled* endpoint config for the given
        agent type. Falls back to ``default_llm_cfg`` if no custom endpoints
        are configured or all are disabled.

        Args:
            agent_type: The agent type to resolve config for
        """
        chain = self.get_endpoint_chain(agent_type)
        if chain:
            return chain[0]
        return copy.deepcopy(self.default_llm_cfg)

    def get_effective_max_tokens(self, agent_type: str) -> int:
        """
        Returns the effective max_input_tokens for an agent type.
        
        Uses the per-endpoint value if configured, otherwise falls back to
        the general settings value. The general settings is a fallback only,
        not a hard cap — each agent type keeps its own configured limit.
        """
        # Read general_limit AND resolve endpoint chain inside a single lock scope
        # to ensure atomicity — no risk of general_limit changing mid-computation.
        ep_limit = 0
        general_limit = 0
        with self._lock:
            defaults = self.default_llm_cfg or {}
            general_limit = defaults.get('max_input_tokens', 0)
            
            # Normalize agent_type for case-insensitive lookup (Fix Finding 1)
            normalized_agent_type = self._normalize_agent_type(agent_type)
            
            for eid in self.agent_priorities.get(normalized_agent_type, []):
                ep = self.endpoints.get(eid)
                if ep and ep.enabled:
                    ep_limit = ep.max_input_tokens
                    break
        
        # Use endpoint-specific limit; fall back to general settings only when endpoint has none configured
        if ep_limit > 0:
            return ep_limit
        if general_limit > 0:
            return general_limit
        return 0

    def _normalize_agent_type(self, agent_type: str) -> str:
        """
        Normalize agent_type for case-insensitive lookup.
        
        Frontend stores priorities with PascalCase keys (e.g., "Coder", "Security")
        while backend uses lowercase during streaming (e.g., "coder", "security").
        This method performs case-insensitive lookup to ensure live updates work.
        
        Returns the canonical key from agent_priorities if found, otherwise returns
        the canonical form from CANONICAL_AGENT_TYPES or the original agent_type.
        
        CONTRACT: Must be called under self._lock to prevent concurrent modification.
        """
        # Fix Finding 4: Strip whitespace before processing
        if not agent_type:
            return agent_type
        
        agent_type = agent_type.strip()
        if not agent_type:
            return agent_type
        
        agent_type_lower = agent_type.lower()
        
        # Fix Finding 2: Take a snapshot of keys to prevent concurrent modification issues
        existing_keys_snapshot = list(self.agent_priorities.keys())
        
        # Try exact match first (fastest path)
        if agent_type in self.agent_priorities:
            return agent_type
        
        # Case-insensitive fallback - check existing keys first
        for key in existing_keys_snapshot:
            if key.lower() == agent_type_lower:
                return key
        
        # If no match found, return the canonical form (Fix Finding 3)
        # This ensures consistent behavior across restarts regardless of source ordering
        return CANONICAL_AGENT_TYPES.get(agent_type_lower, agent_type)

    @staticmethod
    def _adjust_config_for_tokens(cfg: dict, allocated_tokens: Optional[int]) -> None:
        """Adjust max_input_tokens in cfg if allocated_tokens is provided and would exceed the configured limit."""
        if allocated_tokens is not None:
            effective_limit = cfg.get('max_input_tokens', 0)
            if effective_limit > 0 and effective_limit < allocated_tokens:
                cfg['max_input_tokens'] = allocated_tokens

    def get_endpoint_chain(
        self,
        agent_type: str,
        allocated_tokens: Optional[int] = None,
        instance_name: Optional[str] = None,
    ) -> List[dict]:
        """
        Returns an ordered list of LLM configs to try for the given agent type:
          1. Agent-specific endpoints (priority order, enabled only) — Tier 1
          2. Last successful endpoint (if available and validated) — Tier 3
          3. General Settings default (always last) — Tier 4

        Priority order is preserved as configured by the user. Images are captioned
        upstream so any endpoint in the chain can handle them without reordering,
        ensuring the admin's preferred endpoint always gets tried first.

        When ``instance_name`` is provided, the returned chain is rotated to start
        from that instance's tracked cursor position (see :meth:`advance_instance_endpoint`).
        This enables "kick to next endpoint" — after inner-loop detection, retries
        skip past endpoints that already failed instead of starting from index 0.

        NOTE: There is no caller-inheritance tier. Every agent resolves through its own
        Tier 1 → Tier 3 → Tier 4 chain (single FIFO slot system). An unconfigured agent
        falls to the last-successful / global default, exactly like any other agent.

        Args:
            agent_type: The type of agent requesting endpoints
            allocated_tokens: Optional - the agent's allocated context size in tokens.
                            When provided, used to filter/weight endpoint selection for sufficient capacity.
            instance_name:  Optional - when provided, rotates chain starting from
                          this instance's tracked cursor position (per-instance memory).
        """
        # Read general_limit inside lock scope for thread safety (same pattern as get_effective_max_tokens)
        general_limit = 0
        endpoint_configs = []

        # Agent-specific endpoints — under lock to prevent RuntimeError from concurrent dict modification
        with self._lock:
            defaults = self.default_llm_cfg or {}
            general_limit = defaults.get('max_input_tokens', 0)
            
            own_endpoints, _had_own = self._resolve_own_endpoints(agent_type)

            # Normalize for downstream checks
            normalized_agent_type = self._normalize_agent_type(agent_type)

            # Build configs from the agent's own (Tier 1) endpoints
            for eid, ep in own_endpoints:
                cfg = ep.to_llm_cfg()

                # Apply token limits and dynamic adjustment
                ep_limit = ep.max_input_tokens
                if ep_limit <= 0 and general_limit > 0:
                    cfg['max_input_tokens'] = general_limit

                self._adjust_config_for_tokens(cfg, allocated_tokens)
                endpoint_configs.append(cfg)

            # Tier 3: Last successful endpoint fallback — only for agents that ever had priorities configured
            if not endpoint_configs and self._last_successful_endpoint_cfg is not None:
                if normalized_agent_type not in self._agent_types_with_priorities:
                    logger.debug(f"[APIRouter] Skipping Tier 3 fallback for '{normalized_agent_type}' (no priorities configured)")
                else:
                    last_success_cfg = self._last_successful_endpoint_cfg
                    # Validate last successful endpoint still exists and is enabled
                    api_base = last_success_cfg.get('api_base') or last_success_cfg.get('model_server', '')
                    for ep in self.endpoints.values():
                        if ep.api_base == api_base and ep.enabled:
                            cfg = copy.deepcopy(last_success_cfg)
                            ep_limit = ep.max_input_tokens
                            if ep_limit <= 0 and general_limit > 0:
                                cfg['max_input_tokens'] = general_limit
                            
                            self._adjust_config_for_tokens(cfg, allocated_tokens)
                            endpoint_configs.append(cfg)
                            logger.debug(f"[APIRouter] Using Tier 3 fallback for '{normalized_agent_type}': {api_base}")
                            break

            # Filter out endpoints currently in cooldown period.
            # Default endpoint is appended after filtering, so it's always available as last resort.
            # NOTE: Already under self._lock from outer scope — read _endpoint_failure_times directly.
            if ENDPOINT_COOLDOWN_SECONDS > 0 and endpoint_configs:
                now = time.time()
                filtered_configs = []
                skipped_count = 0
                for cfg in endpoint_configs:
                    api_base = cfg.get('api_base') or cfg.get('model_server', '')
                    last_fail = self._endpoint_failure_times.get(api_base, 0)
                    if api_base and (now - last_fail) < ENDPOINT_COOLDOWN_SECONDS:
                        skipped_count += 1
                        logger.debug(
                            f"[APIRouter] Skipping endpoint '{cfg.get('model', 'unknown')}' @ {api_base} "
                            f"in cooldown ({ENDPOINT_COOLDOWN_SECONDS - int(now - last_fail)}s remaining)"
                        )
                    else:
                        filtered_configs.append(cfg)
                if skipped_count > 0:
                    endpoint_configs = filtered_configs if filtered_configs else []
                    logger.info(
                        f"[APIRouter] Endpoint cooldown: skipped {skipped_count} endpoint(s), "
                        f"{len(endpoint_configs)} available for '{normalized_agent_type}'"
                    )

            # Tier 4: Always append the default as last resort — inside lock so cursor rotation reads atomically
            if self.default_llm_cfg is not None:
                endpoint_configs.append(copy.deepcopy(self.default_llm_cfg))
            
            # Adjust default endpoint for allocated tokens requirement (dynamic endpoint selection)
            if endpoint_configs:
                self._adjust_config_for_tokens(endpoint_configs[-1], allocated_tokens)

            # Per-instance cursor rotation: rotate chain from tracked position to skip previously-failed endpoints.
            # Done inside lock to atomically read cursor and return a consistent rotated view.
            if instance_name and len(endpoint_configs) > 1:
                tier_count = len(endpoint_configs) - 1  # Everything except the default (Tier 3)
                cursor = self._instance_endpoint_position.get(instance_name, 0)
                default_cfg = endpoint_configs[-1]
                tier_configs = endpoint_configs[:tier_count]

                if tier_count == 1:
                    if cursor > 0:
                        endpoint_configs = [default_cfg] + tier_configs
                else:
                    effective_cursor = cursor % tier_count
                    if effective_cursor > 0:
                         rotated_tiers = tier_configs[effective_cursor:] + tier_configs[:effective_cursor]
                         endpoint_configs = rotated_tiers + [default_cfg]
                         logger.debug(f"[APIRouter] Endpoint cursor for '{instance_name}' rotated by {effective_cursor}")
                         
        # Validate: no endpoint configured at all
        if not endpoint_configs:
            raise ValueError(
                f"No LLM endpoint configured for agent type '{agent_type}'. "
                f"Set endpoints in General Settings or assign endpoints to this agent type."
            )

        # Validate: only config available is incomplete (missing both api_base and model)
        if len(endpoint_configs) == 1:
            only_cfg = endpoint_configs[0]
            has_api_base = bool(only_cfg.get('api_base') or only_cfg.get('model_server'))
            has_model = bool(only_cfg.get('model'))
            if not has_api_base and not has_model:
                raise ValueError(
                    f"No usable LLM endpoint configured for agent type '{agent_type}'. "
                    f"Configure api_base and model in General Settings or assign endpoints to this agent type."
                )

        # Validate: at least one config in the chain has required fields (multi-config case)
        if endpoint_configs:
            has_valid = any(
                bool(cfg.get('api_base') or cfg.get('model_server'))
                for cfg in endpoint_configs
            )
            if not has_valid:
                raise ValueError(
                    f"No usable LLM endpoint configured for agent type '{agent_type}'. "
                    f"All endpoints in the fallback chain are missing api_base. "
                    f"Configure endpoints in General Settings or assign endpoints to this agent type."
                )

        return endpoint_configs

    # ── Per-Instance Endpoint Cursor Management ───────────────────────────
    # Manages the "kick to next endpoint" mechanism. When inner-loop detection
    # happens, execution_engine calls advance_instance_endpoint() to move past
    # the failing endpoint before retrying. On success or dismissal, the cursor
    # is reset so the instance starts fresh from index 0 again.

    def advance_instance_endpoint(self, instance_name: str) -> int:
        """Advance endpoint cursor by one for the given instance (called on inner-loop detection)."""
        if not instance_name:
            return 0
        with self._lock:
            pos = self._instance_endpoint_position.get(instance_name, 0) + 1
            self._instance_endpoint_position[instance_name] = pos
            logger.debug(
                f"[APIRouter] Endpoint cursor advanced for '{instance_name}': "
                f"position {pos - 1} → {pos}. Next call will skip past this endpoint."
            )
        return pos

    def reset_instance_endpoint(self, instance_name: str) -> None:
        """Reset endpoint cursor to zero for the given instance (called on success/dismissal)."""
        if not instance_name:
            return
        with self._lock:
            old_pos = self._instance_endpoint_position.pop(instance_name, None)
            if old_pos is not None and old_pos > 0:
                logger.debug(
                    f"[APIRouter] Endpoint cursor reset for '{instance_name}': "
                    f"position {old_pos} → 0 (cleaned up)."
                )

    @staticmethod
    def _is_context_exceeded_error(error: Exception) -> bool:
        """Check if an error indicates the input exceeded the model's context window.

        llama.cpp returns HTTP 400 with "exceed_context_size_error" in body.
        Other servers may use different patterns — catch them too.
        """
        # Already a typed ContextWindowExceeded exception
        if isinstance(error, ContextWindowExceeded):
            return True

        err_str = str(error).lower()
        from agent_cascade.llm.base import ModelServiceError
        code = getattr(error, 'code', None)

        # llama.cpp and similar servers: HTTP 400 with context-size patterns
        if code == '400' and any(
            pattern in err_str
            for pattern in ('exceed_context_size', 'context length', 'maximum input context', 'context window')
        ):
            return True

        # Generic patterns from various servers
        if any(
            pattern in err_str
            for pattern in ('prompt is too long', 'input tokens exceed', 'max_tokens exceeded', 'exceeds the context limit')
        ):
            return True

        return False

    def _cleanup_stale_failure_records(self, now: float) -> None:
        """Remove failure records older than ENDPOINT_FAILURE_CLEANUP_HOURS to prevent unbounded growth."""
        if not self._endpoint_failure_times:
            return
        cutoff = now - (ENDPOINT_FAILURE_CLEANUP_HOURS * 3600)
        stale_keys = [api_base for api_base, ts in self._endpoint_failure_times.items() if ts < cutoff]
        if stale_keys:
            for key in stale_keys:
                del self._endpoint_failure_times[key]
            logger.debug(
                f"[APIRouter] Cleaned up {len(stale_keys)} stale endpoint failure record(s) "
                f"(older than {ENDPOINT_FAILURE_CLEANUP_HOURS}h)"
            )

    # ── Retry + Fallback Execution ───────────────────────────────────────

    def call_with_fallback(
        self,
        agent_type: str,
        call_fn: Callable,
        *args,
        allocated_tokens: Optional[int] = None,
        **kwargs
    ) -> Any:
        """
        Execute ``call_fn(*args, **kwargs)`` with automatic endpoint fallback.
        Supports both regular functions and generators.

        Concurrency is controlled at the agent lifecycle level via SlotPool
        (acquired before the turn starts). No per-call gating occurs here.

        Args:
            agent_type: The type of agent making the call (e.g., 'coder', 'researcher')
            call_fn: The function to execute with the selected endpoint config
            allocated_tokens: Optional - the agent's allocated context size in tokens.
                           When provided, used for endpoint selection to ensure sufficient capacity.
            *args, **kwargs: Additional arguments passed to call_fn. If ``agent_instance_name``
                          is present it is forwarded as ``instance_name`` to rotate the chain.
        """
        # Extract instance name from kwargs (set by execution_engine) so we can
        # apply per-instance cursor rotation and skip already-failed endpoints.
        _inst_name = kwargs.pop('agent_instance_name', None)
        chain = self.get_endpoint_chain(
            agent_type, allocated_tokens=allocated_tokens, instance_name=_inst_name,
        )
        all_errors = []

        for cfg_idx, llm_cfg in enumerate(chain):
            # Default per-endpoint retry count from policy. Endpoint config (max_retries field)
            # overrides this — explicit endpoint max_retries always takes precedence.
            max_retries = self.policy.endpoint_max_retries
            
            concurrency_limit = 0
            rate_limit_rpm = 0           # Default: unlimited
            is_default = (cfg_idx == len(chain) - 1)
            
            # Resolve endpoint-specific settings — always try to read from
            # the endpoint config, even for the default fallback endpoint.
            # The default endpoint may also be in self.endpoints with its own
            # concurrency setting (Phase 1 fix).
            endpoint_base = llm_cfg.get('api_base') or llm_cfg.get('model_server', 'unknown')
            with self._lock:
                for ep in self.endpoints.values():
                    if ep.api_base == endpoint_base:
                        max_retries = ep.max_retries
                        concurrency_limit = ep.concurrency_limit
                        rate_limit_rpm = ep.rate_limit_rpm
                        break
            
            def execute_api_call():
                """Execute the API call. The agent already holds its endpoint's lifecycle slot for this turn."""
                result = call_fn(llm_cfg, *args, **kwargs)
                if not isinstance(result, (list, dict, str)) and hasattr(result, '__iter__'):
                    # Generator — pull first chunk to detect API errors early
                    it = iter(result)
                    try:
                        first_chunk = next(it)
                    except StopIteration:
                        return iter([])

                    def _gen_wrapper(first, rest):
                        yield first
                        try:
                            yield from rest
                        finally:
                            # Close the underlying generator to release HTTP connection
                            try:
                                rest.close()
                            except Exception:
                                pass
                    return _gen_wrapper(first_chunk, it)

                return result

            endpoint_name = llm_cfg.get('model', 'unknown')

            for attempt in range(max_retries + 1):
                # Check if instance was terminated during a previous failed attempt or between retries.
                # Prevents starting new API calls after termination (does not interrupt mid-stream calls).
                if self._pool and _inst_name:
                    if _inst_name in self._pool.terminated_instances:
                        logger.debug(f"[TERMINATION] Instance '{_inst_name}' terminated, aborting LLM call")
                        raise RuntimeError(f"Instance '{_inst_name}' has been terminated")

                try:
                    # Rate limiting: check and enforce per-endpoint rate limit before each call attempt.
                    # Each retry attempt counts against the rate limit.
                    if rate_limit_rpm > 0:
                        with self._lock:
                            if endpoint_base not in self._endpoint_call_history:
                                self._endpoint_call_history[endpoint_base] = collections.deque()
                        # Loop until we successfully record this call (handles race conditions when multiple threads sleep)
                        while True:
                            now = time.time()
                            wait_time = 0.0
                            with self._lock:
                                history = self._endpoint_call_history[endpoint_base]
                                # Sliding window: remove calls older than RATE_LIMIT_WINDOW_SECONDS
                                while history and now - history[0] >= RATE_LIMIT_WINDOW_SECONDS:
                                    history.popleft()
                                # Check if we're over the limit — calculate wait time instead of raising
                                if len(history) >= rate_limit_rpm:
                                    wait_time = RATE_LIMIT_WINDOW_SECONDS - (now - history[0])
                            # Sleep outside the lock to avoid blocking other threads
                            if wait_time > 0:
                                logger.debug(
                                    f"[APIRouter] Rate limit reached for '{endpoint_name}' @ {endpoint_base}. "
                                    f"Waiting {wait_time:.1f}s before next call ({rate_limit_rpm} rpm)"
                                )
                                # Interruptible sleep: check termination every 0.5s during rate-limit wait
                                _interruptible_sleep(wait_time, self._pool, _inst_name)
                            # After sleeping, re-check and try to record (loop handles contention)
                            with self._lock:
                                now = time.time()
                                history = self._endpoint_call_history[endpoint_base]
                                while history and now - history[0] >= RATE_LIMIT_WINDOW_SECONDS:
                                    history.popleft()
                                if len(history) < rate_limit_rpm:
                                    # Track this call atomically within the same lock to prevent race conditions
                                    history.append(now)
                                    break  # Successfully recorded, exit loop
                    
                    # Check termination again just before making the actual API call,
                    # in case instance was terminated during rate limit wait or backoff.
                    if self._pool and _inst_name:
                        if _inst_name in self._pool.terminated_instances:
                            logger.debug(f"[TERMINATION] Instance '{_inst_name}' terminated before API call, aborting")
                            raise RuntimeError(f"Instance '{_inst_name}' has been terminated")

                    result = execute_api_call()
                    
                    # Track the last successful endpoint config for automatic recovery.
                    # Stored only after complete success (including all retries), not during retries.
                    # This enables Tier 3 (last-successful) fallback when agent-specific endpoints become unavailable.
                    with self._lock:
                        self._last_successful_endpoint_cfg = copy.deepcopy(llm_cfg)
                    
                    # Generator errors are already detected inside execute_api_call (first-chunk pull).
                    # Pass the generator through directly — no double-wrapping needed.
                    return result
                    
                except Exception as e:
                    # AgentTerminatedError is a clean abort signal — re-raise immediately
                    # without logging, retrying, or moving to next endpoint.
                    if isinstance(e, AgentTerminatedError):
                        raise
                    
                    err_msg = str(e)

                    # Detect context window exceeded errors and advance cursor.
                    # Unlike CharacterRunDetected/MaxTokenExceeded (which occur during streaming
                    # in execution_engine), context-exceeded happens here at API call time.
                    # Advance the per-instance cursor so engine-level retries skip past this endpoint.
                    _inst_name_for_cursor = _inst_name  # Use the variable extracted at call time (kwargs.pop removed it)
                    if _inst_name_for_cursor and self._is_context_exceeded_error(e):
                        # For Compressor agents: just advance cursor (they handle their own compression)
                        if agent_type.lower().startswith('compressor'):
                            new_pos = self.advance_instance_endpoint(_inst_name_for_cursor)
                            logger.warning(
                                f"[APIRouter] Context window exceeded for Compressor '{_inst_name_for_cursor}' "
                                f"on endpoint '{endpoint_name}'. Cursor advanced to {new_pos}."
                            )
                        else:
                            # Advance cursor NOW so retry uses a different (hopefully larger) endpoint after compression.
                            new_pos = self.advance_instance_endpoint(_inst_name_for_cursor)
                            logger.warning(
                                f"[APIRouter] Context window exceeded for '{_inst_name_for_cursor}' "
                                f"on endpoint '{endpoint_name}'. Triggering iterative fallback compression. "
                                f"Cursor advanced to {new_pos}."
                            )
                            # Lazy import to avoid potential circular imports
                            from agent_cascade.exceptions import FallbackCompressionRequired
                            raise FallbackCompressionRequired(
                                _inst_name_for_cursor, agent_type, endpoint_name, original_error=e
                            ) from e

                    # NOTE: CharacterRunDetected/MaxTokenExceeded exceptions are raised during
                    # generator iteration inside execution_engine.py, after this method has returned.
                    # All endpoint advancement for those errors happens via
                    # _handle_inner_loop_detection → advance_instance_endpoint.
                    # This block only handles connection/timeout/etc. errors from execute_api_call.

                    # All errors (connection, timeout, etc.) retry within the current
                    # endpoint first, then cascade through the fallback chain on exhaustion.
                    tb_str = traceback.format_exc()
                    error_msg = (
                        f"Endpoint '{endpoint_name}' @ {endpoint_base} "
                        f"attempt {attempt+1}/{max_retries+1}: {e}\nTraceback: {tb_str}"
                    )
                    logger.warning(f"[APIRouter] {error_msg}")
                    all_errors.append(error_msg)

                    if attempt < max_retries:
                        # Use centralized backoff policy (consistent with execution engine)
                        delay = calculate_backoff(attempt + 1, self.policy)
                        logger.info(
                            f"[APIRouter] Backing off {delay:.1f}s before retry "
                            f"for endpoint '{endpoint_name}' @ {endpoint_base}"
                        )
                        # Interruptible sleep: check termination every 0.5s during retry backoff
                        _interruptible_sleep(delay, self._pool, _inst_name)

            logger.info(f"[APIRouter] Exhausted retries for endpoint '{endpoint_name}'. Moving to next...")
            
            # Record failure time for cooldown tracking when abandoning this endpoint after all retries.
            # Rate limit waits are self-imposed throttles, not real failures — only record on actual exhaustion.
            if ENDPOINT_COOLDOWN_SECONDS > 0:
                now = time.time()
                with self._lock:
                    # Clean up stale records to prevent unbounded growth
                    self._cleanup_stale_failure_records(now)
                    self._endpoint_failure_times[endpoint_base] = now
                logger.debug(
                    f"[APIRouter] Endpoint '{endpoint_name}' @ {endpoint_base} marked as failed. "
                    f"Cooldown for {ENDPOINT_COOLDOWN_SECONDS}s."
                )

        raise RuntimeError(
            f"All API endpoints exhausted for agent type '{agent_type}'.\n"
            + "\n".join(all_errors)
        )

    # ── Image Captioning ─────────────────────────────────────────────────
    # When images lack captions and the target endpoint is text-only, generate
    # a caption using any available vision-capable endpoint.

    CAPTION_PROMPT = (
        "Describe this image in one concise sentence suitable for use as an alt-text description. "
        "Focus on key visual elements: objects, people, colors, layout, and any text visible."
    )

    @staticmethod
    def _has_uncaptioned_images(messages):
        """Check if any message contains images without captions."""
        from agent_cascade.llm.schema import ContentItem
        for msg in messages:
            if isinstance(msg.content, list):
                for item in msg.content:
                    if isinstance(item, dict) and item.get('image'):
                        if not item.get('caption'):
                            return True
                    elif hasattr(item, 'image') and item.image:
                        if not getattr(item, 'caption', None):
                            return True
        return False

    def _get_any_vision_endpoint(self) -> Optional[dict]:
        """Return the config of any enabled vision-capable endpoint."""
        with self._lock:
            for ep in self.endpoints.values():
                if ep.enabled and getattr(ep, 'vision_enabled', True):
                    return ep.to_llm_cfg()
            # Fallback: default config (assume vision by default)
            if self.default_llm_cfg:
                cfg = copy.deepcopy(self.default_llm_cfg)
                cfg.setdefault('vision_enabled', True)
                return cfg
        return None

    def _get_vision_endpoint_for_agent(self, agent_type: str) -> Optional[dict]:
        """Return the first vision-capable endpoint from the agent's own endpoint chain.

        Falls back to any vision endpoint if none in the chain has vision.
        """
        chain = self.get_endpoint_chain(agent_type)
        for cfg in chain:
            if cfg.get('vision_enabled', True):
                return cfg
        # Fallback: any vision endpoint
        return self._get_any_vision_endpoint()

    def caption_images(
        self, messages, agent_type: str = 'generalist'
    ) -> List:
        """
        Generate captions for uncaptioned images in the message list.

        Uses the agent's own endpoint chain to find a vision-capable endpoint
        for captioning, preserving the agent's configured endpoint order.

        Args:
            messages: List of Message objects (may contain images)
            agent_type: Agent type used for endpoint resolution

        Returns:
            Modified message list with captions attached to images.
        """
        if not self._has_uncaptioned_images(messages):
            return messages

        from agent_cascade.llm.schema import ContentItem, Message
        vision_cfg = self._get_vision_endpoint_for_agent(agent_type)
        if not vision_cfg:
            # Replace uncaptioned images with placeholder text to ensure safe fallback
            logger.warning("[APIRouter] No vision-capable endpoint found for image captioning — replacing with placeholders")
            for msg in messages:
                items = msg.content if isinstance(msg.content, list) else []
                for item in items:
                    img_val = item.get('image') if isinstance(item, dict) else getattr(item, 'image', None)
                    existing_caption = item.get('caption') if isinstance(item, dict) else getattr(item, 'caption', None)
                    if img_val and not existing_caption:
                        cap = '[Image]'
                        if isinstance(item, dict):
                            item['caption'] = cap
                        else:
                            item.caption = cap
            return messages

        from agent_cascade.llm import get_chat_model

        # Collect all uncaptioned images for batch processing
        uncaptioned_items = []  # (msg_index, item_index) tuples to patch back

        for msg_idx, msg in enumerate(messages):
            items = msg.content if isinstance(msg.content, list) else []
            for item_idx, item in enumerate(items):
                img_val = item.get('image') if isinstance(item, dict) else getattr(item, 'image', None)
                existing_caption = item.get('caption') if isinstance(item, dict) else getattr(item, 'caption', None)
                if img_val and not existing_caption:
                    uncaptioned_items.append((msg_idx, item_idx, img_val))

        if not uncaptioned_items:
            return messages

        # Process each uncaptioned image individually for accurate captions
        all_captions = {}  # key = (msg_idx, item_idx) -> caption text
        
        # Batch: send prompt + one image at a time to get per-image captions
        for msg_idx, item_idx, img_val in uncaptioned_items:
            try:
                chat_model = get_chat_model(vision_cfg)
                cap_msg = Message(
                    role='user',
                    content=[
                        ContentItem(text=self.CAPTION_PROMPT),
                        ContentItem(image=img_val),
                    ]
                )
                result_iter = chat_model.chat(
                    messages=[cap_msg],
                    stream=True,
                    delta_stream=False,
                    extra_generate_cfg=vision_cfg,
                )
                # Consume the generator to get the final response
                last_chunk = None
                for chunk in result_iter:
                    last_chunk = chunk
                if last_chunk and len(last_chunk) > 0:
                    caption_text = ''
                    for m in last_chunk:
                        # Handle both Message objects and dicts returned by chat models
                        content = getattr(m, 'content', None) or (m.get('content') if isinstance(m, dict) else None)
                        if isinstance(content, str):
                            caption_text += content
                        elif isinstance(content, list):
                            for ci in content:
                                txt = getattr(ci, 'text', '') or (ci.get('text') if isinstance(ci, dict) else '')
                                if txt:
                                    caption_text += txt
                    caption_text = caption_text.strip()[:MAX_CAPTION_LENGTH]  # Cap length to avoid bloating messages
                else:
                    caption_text = '[Image]'
            except Exception as e:
                logger.warning(f"[APIRouter] Failed to generate image caption: {e}")
                caption_text = '[Image]'

            all_captions[(msg_idx, item_idx)] = caption_text

        # Patch captions back into messages in-place
        for msg_idx, item_idx, _ in uncaptioned_items:
            key = (msg_idx, item_idx)
            caption = all_captions.get(key, '[Image]')
            items = messages[msg_idx].content if isinstance(messages[msg_idx].content, list) else []
            if item_idx < len(items):
                item = items[item_idx]
                if isinstance(item, dict):
                    item['caption'] = caption
                else:
                    item.caption = caption

        logger.info(f"[APIRouter] Captioned {len(uncaptioned_items)} image(s) for vision fallback")
        return messages

    # ── Persistence ──────────────────────────────────────────────────────

    def _save(self):
        """Persist config to disk."""
        try:
            self._config_dir.mkdir(parents=True, exist_ok=True)
            data = {
                'endpoints': [ep.to_dict() for ep in self.endpoints.values()],
                'agent_priorities': self.agent_priorities,
                'agent_types_with_priorities': list(self._agent_types_with_priorities),
            }
            with open(self._config_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
        except Exception as e:
            logger.error(f"[APIRouter] Failed to save config: {e}")

    def _normalize_agent_priorities(self, priorities: dict) -> dict:
        """
        Normalize agent_priorities dict to remove case-insensitive duplicate keys.
        
        When both 'Coder' and 'coder' exist, keeps the first one encountered
        (typically PascalCase from frontend). This prevents double entries in UI.
        
        Args:
            priorities: Raw agent_priorities dict that may have duplicates
            
        Returns:
            Normalized dict with only one key per agent type (case-insensitive)
        """
        normalized = {}
        seen_lower = {}  # Maps lowercase key -> canonical key to track which we kept
        
        for key, value in priorities.items():
            if not key:
                continue
                
            key_lower = key.lower()
            if key_lower not in seen_lower:
                # First occurrence - keep it
                normalized[key] = value
                seen_lower[key_lower] = key
            # Else: duplicate found, skip this one (keep the first)
        
        if len(normalized) != len(priorities):
            logger.info(
                f"[APIRouter] Normalized agent_priorities: {len(priorities)} keys → "
                f"{len(normalized)} keys (removed {len(priorities) - len(normalized)} case duplicates)"
            )
        
        return normalized

    def _load(self):
        """Load config from disk if available.

        If the file does not exist, it is created with an empty default
        configuration and a warning is logged so the user knows to configure
        at least one LLM endpoint.
        """
        if not self._config_path.exists():
            # Auto-create with safe defaults on first startup.
            try:
                self._config_dir.mkdir(parents=True, exist_ok=True)
                default_config = {
                    "endpoints": [],
                    "agent_priorities": {},
                    "agent_types_with_priorities": [],
                }
                with open(self._config_path, 'w', encoding='utf-8') as f:
                    json.dump(default_config, f, indent=2)
                logger.warning(
                    "config/api_endpoints.json not found; created with empty default configuration. "
                    "Please configure at least one LLM endpoint."
                )
            except OSError as e:
                logger.error(f"[APIRouter] Failed to create config/api_endpoints.json: {e}")
            return
        try:
            with open(self._config_path, 'r', encoding='utf-8-sig') as f:
                content = f.read().strip()
                if not content:
                    return
                data = json.loads(content)

            if not isinstance(data, dict):
                logger.warning(f"[APIRouter] Config file {self._config_path} is not a dictionary. Skipping.")
                return

            for ep_data in data.get('endpoints', []):
                try:
                    ep = APIEndpoint.from_dict(ep_data)
                    self.endpoints[ep.id] = ep
                except Exception as e:
                    logger.error(f"[APIRouter] Failed to parse endpoint data: {e}")

            # Normalize agent_priorities to remove case-insensitive duplicates
            raw_priorities = data.get('agent_priorities', {})
            self.agent_priorities = self._normalize_agent_priorities(raw_priorities)
            
            # Load tracking set for agent types that ever had endpoints configured.
            # This gates the Tier 3 (last-successful) fallback: agents with no configuration should go straight to global default.
            # For backward compatibility, if the field is missing (old config), we infer it from current priorities.
            raw_tracked = data.get('agent_types_with_priorities', [])
            if raw_tracked:
                self._agent_types_with_priorities = set(raw_tracked)
            else:
                # Backward compat: any agent type with current priorities was clearly configured at some point
                self._agent_types_with_priorities = set(self.agent_priorities.keys())
            
            # Sync tracking set with actual priorities — remove any stale entries from old configs.
            # Prevents incorrect Tier 3 (last-successful) fallback if config has tracked types without actual priorities.
            self._agent_types_with_priorities &= set(self.agent_priorities.keys())
            
            logger.info(f"[APIRouter] Loaded {len(self.endpoints)} endpoints from {self._config_path}")
        except Exception as e:
            logger.error(f"[APIRouter] Failed to load config from {self._config_path}: {e}")

    # ── Serialization (for UI transport) ─────────────────────────────────

    def to_dict(self) -> dict:
        """Full serialization for WebSocket state broadcast."""
        return {
            'endpoints': [ep.to_dict() for ep in self.endpoints.values()],
            'agent_priorities': copy.deepcopy(self.agent_priorities),
        }

    def from_dict(self, data: dict):
        """
        Load full state from a dict (e.g. from UI update).
        
        Normalizes agent_priorities to prevent duplicate keys from case mismatches
        between frontend and backend updates.
        """
        with self._lock:
            # Parse endpoints into a temporary dict first — don't clear existing endpoints yet.
            # This prevents leaving the router in a corrupted (empty) state if parsing fails mid-way.
            new_endpoints = {}
            for ep_data in data.get('endpoints', []):
                try:
                    ep = APIEndpoint.from_dict(ep_data)
                    new_endpoints[ep.id] = ep
                except Exception as e:
                    logger.error(f"[APIRouter.from_dict] Failed to parse endpoint data: {e}")
            
            # Swap atomically only after all parsing succeeds
            self.endpoints.clear()
            self.endpoints.update(new_endpoints)
            
            # Normalize agent_priorities to remove case-insensitive duplicates
            raw_priorities = data.get('agent_priorities', {})
            self.agent_priorities = self._normalize_agent_priorities(raw_priorities)
            self._agent_types_with_priorities = set(self.agent_priorities.keys())
            
            ep_ids = list(self.endpoints.keys())
            logger.info(f"[APIRouter.from_dict] Updated: {len(self.endpoints)} endpoints "
                       f"({ep_ids}) with "
                       f"{len(self.agent_priorities)} priority mappings: "
                       f"{dict(self.agent_priorities)}")
            self._save()

    def update_default_llm_cfg(self, new_cfg: dict):
        """
        Update the default fallback config (from General Settings changes).
        
        Note: This is a partial update — only keys present in new_cfg are updated.
        Keys removed from the UI will persist in default_llm_cfg until explicitly overwritten.
        """
        with self._lock:
            # Defensive: ensure default_llm_cfg is not None
            if self.default_llm_cfg is None:
                self.default_llm_cfg = {}
            
            # Log which keys are being updated (for debugging config propagation issues)
            # Only keys present in new_cfg are checked; keys removed from the UI persist in default_llm_cfg
            changed_keys = [k for k in new_cfg if k not in self.default_llm_cfg or self.default_llm_cfg[k] != new_cfg[k]]
            if changed_keys:
                logger.info(f"[APIRouter.update_default_llm_cfg] Updating {len(changed_keys)} keys: {changed_keys}")
            self.default_llm_cfg.update(new_cfg)

    def is_waiting(self, agent_name: str) -> bool:
        """Check if an agent instance is currently waiting for a slot in the FIFO queue."""
        for pool in self.scheduler._pools.values():
            status = pool.get_status()
            for waiter in status.get('waiters', []):
                if waiter.get('instance_name') == agent_name:
                    return True
        return False
