"""API endpoint config: initializer, constants, APIEndpoint dataclass, repeat-penalty helper.

Moved verbatim from api_router.py (Phase 3a pure-move refactor).
"""

import json
import logging
import uuid
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, Optional

logger = logging.getLogger(__name__)

def ensure_api_endpoints_config(config_dir: Optional[str] = None) -> bool:
    """
    Ensure api_endpoints.json exists at startup without instantiating APIRouter.

    Returns True if the file already existed or was created successfully, False on failure.
    """
    try:
        if config_dir is not None:
            config_path = Path(config_dir) / 'api_endpoints.json'
        else:
            # Project-root config dir (same logic as APIRouter.__init__)
            project_root = Path(__file__).resolve().parent.parent
            config_path = project_root / 'config' / 'api_endpoints.json'

        if config_path.exists():
            return True

        config_path.parent.mkdir(parents=True, exist_ok=True)
        default_config = {
            "endpoints": [],
            "agent_priorities": {},
            "agent_types_with_priorities": [],
        }
        with open(config_path, 'w', encoding='utf-8') as f:
            json.dump(default_config, f, indent=2)

        logger.warning(
            "config/api_endpoints.json not found; created with empty default configuration. "
            "Please configure at least one LLM endpoint."
        )
        return True
    except OSError as e:
        logger.error("[INIT] Failed to create config/api_endpoints.json: %s", e)
        return False

MAX_CAPTION_LENGTH = 300              # Maximum length for image captions generated by vision model
RATE_LIMIT_WINDOW_SECONDS = 60        # Sliding window (seconds) for per-endpoint rate-limit tracking

# Canonical agent type mapping for case-insensitive normalization and idempotency
# Maps lowercase agent types to their canonical PascalCase form
CANONICAL_AGENT_TYPES: Dict[str, str] = {
    "coder": "Coder",
    "researcher": "Researcher",
    "orchestrator": "Orchestrator",
    "security": "Security",
    "writer": "Writer",
    "reviewer": "Reviewer",
    "compressor": "Compressor",
    "generalist": "Generalist",
}


# ── Data Models ──────────────────────────────────────────────────────────────

@dataclass
class APIEndpoint:
    """A single LLM API endpoint configuration."""
    id: str = ""                       # UUID, auto-generated if empty
    name: str = "Unnamed Endpoint"     # Human-friendly label
    api_base: str = ""                 # e.g. "http://localhost:1234/v1"
    api_key: str = "EMPTY"             # API key (may be "EMPTY" for local)
    model: str = ""                    # Model name/ID
    model_type: str = "qwenvl_oai"     # "qwenvl_oai", "openai", etc.
    enabled: bool = True               # Toggle on/off without deleting
    max_retries: int = 1               # Per-endpoint retry count before moving to next
    concurrency_limit: int = -1        # -1 = unlimited, 0 = sequential delegation, 1+ = max parallel requests
    max_input_tokens: int = 0          # 0 = unlimited/auto, 1+ = specific limit for this model
    rate_limit_rpm: int = 0            # Rate limit in requests per minute (0 = unlimited)

    # ── Sampler parameters (per-endpoint overrides) ──────────────────────
    temperature: float = 0.0           # 0.0 = use global/default
    top_p: float = 0.0                 # 0.0 = use global/default
    top_k: int = 0                     # 0 = use global/default
    min_p: float = 0.0                 # 0.0 = use global/default
    repeat_penalty: float = 0.0        # 0.0 = use global/default
    presence_penalty: float = 0.0      # 0.0 = use global/default
    frequency_penalty: float = 0.0     # 0.0 = use global/default
    max_tokens: int = 0                # 0 = use global/default

    vision_enabled: bool = True        # Whether this endpoint supports vision
    use_custom_sampling: bool = False  # Master toggle — if False, all sampler params above are ignored
    state_save_enabled: bool = False   # Enable KV cache state save/restore (autoloader only)

    def __post_init__(self):
        if not self.id:
            self.id = str(uuid.uuid4())

    def to_llm_cfg(self) -> dict:
        """Convert to the llm_cfg dict format used by agent_cascade.

        When use_custom_sampling is True, per-endpoint sampler parameters are included.
        Only non-zero values override — zero/empty sentinel values mean "use global/default".
        """
        cfg = {
            'model': self.model,
            'model_server': self.api_base,
            'api_base': self.api_base,
            'api_key': self.api_key,
            'model_type': self.model_type,
            'max_input_tokens': self.max_input_tokens,
            # NOTE: max_retries intentionally excluded — endpoint retry config controls L2 (API router) only.
            # L1 retries are disabled (see llm/base.py). Including this here was the source of coupling.
            'vision_enabled': self.vision_enabled,  # Vision capability flag for routing decisions
            'state_save_enabled': self.state_save_enabled,  # KV cache state save/restore toggle (autoloader only)
        }

        # Signal to _build_merged_cfg whether custom sampling is enabled for this endpoint.
        # When disabled, the merge should strip stale sampling params from lower layers
        # (template defaults / UI overrides) so they don't leak into the LLM call.
        cfg['_use_custom_sampling'] = self.use_custom_sampling

        if self.use_custom_sampling:
            # Only include non-zero sampler params (zero = "use default")
            # Using != 0 consistently so negative values are also captured where valid
            if self.temperature != 0:
                cfg['temperature'] = self.temperature
            if self.top_p != 0:
                cfg['top_p'] = self.top_p
            if self.top_k != 0:
                cfg['top_k'] = self.top_k
            if self.min_p != 0:
                cfg['min_p'] = self.min_p
            rp = self.repeat_penalty
            if rp != 0:
                _normalize_repeat_penalty(cfg, 'repeat_penalty', rp)
            if self.presence_penalty != 0:
                cfg['presence_penalty'] = self.presence_penalty
            if self.frequency_penalty != 0:
                cfg['frequency_penalty'] = self.frequency_penalty
            if self.max_tokens != 0:
                cfg['max_tokens'] = self.max_tokens

        return cfg

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> 'APIEndpoint':
        if not isinstance(data, dict):
            return cls()
        # Filter to only known fields to prevent TypeError on unexpected keys
        known = {f.name for f in cls.__dataclass_fields__.values()}
        filtered = {k: v for k, v in data.items() if k in known}
        return cls(**filtered)

def _normalize_repeat_penalty(cfg: dict, key: str = 'repeat_penalty', val=None) -> None:
    """Add repeat_penalty key variants for backend compatibility.

    If *val* is provided it is used directly; otherwise the value is read from cfg[key].
    All three common naming conventions are written via setdefault so existing entries
    (e.g. already loaded from a config file) take precedence.
    """
    if val is None:
        val = cfg.get(key)
    if val is not None:
        cfg.setdefault('repeat_penalty', val)
        cfg.setdefault('repetition_penalty', val)
        cfg.setdefault('repeatPenalty', val)
